app:
  image: mageinferno/magento2-nginx:1.9
  links:
    - php-fpm
    - db
    - elasticsearch
  volumes_from:
    - appdata
  environment:
    - VIRTUAL_HOST=m2.docker

appdata:
  image: tianon/true
  volumes:
    - ./src:/src
    - ~/.composer:/root/.composer

"php-fpm":
  image: mageinferno/magento2-php:5.6-fpm
  links:
    - db
    - elasticsearch
  volumes_from:
    - appdata

db:
  image: mariadb:10.0
  ports:
    - "8001:3306"
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql
    
elasticsearch:
  image: elasticsearch