<?php
/** @var \Ktpl\Elasticsearch\Helper\Elasticsearch $elasticSearchHelper */
$elasticSearchHelper = $this->helper('Ktpl\Elasticsearch\Helper\Elasticsearch');
$availableFacets = $elasticSearchHelper->getSearchableAttributes();

/* @var $block \Magento\Framework\View\Element\Template */
?>
<div class="block filter" data-bind="scope: 'facets'" data-role="facets-sidebar">
    <div class="block-title filter-title">
        <strong id="block-actions-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Refine Search') ?></strong>
    </div>
    <div class="block-content filter-content">
        <!-- ko if: (appliedFilters().length > 0) -->
        <div class="filter-current" data-collapsible="true" role="tablist">
            <strong class="block-subtitle filter-current-subtitle" role="tab" aria-level="2" data-role="title" data-count="1" aria-selected="false" aria-expanded="false" tabindex="0">Now Shopping by</strong>
            <ol class="items" data-bind="foreach: appliedFilters()">
                <li class="item" data-bind="foreachprop: term">
                    <span class="filter-label" data-bind="text: key"></span>
                    <span class="filter-value" data-bind="text: value"></span>
                    <a class="action remove" href="javascript:void(0)"
                        data-bind="attr : { 'data-item-index': $parentContext.$index, title: 'Remove '+value }">
                        <span><?php echo __('Remove This Item')?></span>
                    </a>
                </li>
            </ol>
        </div>
        <!-- /ko -->
        <!-- ko if: (elasticSearchResults().aggregations) -->
        <div class="filter-options" id="narrow-by-list" data-role="content" role="tablist" data-bind="foreachprop: elasticSearchResults().aggregations">
            <!-- ko if: value.buckets.length -->
            <div data-role="collapsible" class="filter-options-item">
                <div data-role="title" class="filter-options-title" data-bind="text: $parent.service.renderFilter(key)"></div>
                <div data-role="content" class="filter-options-content">
                    <ol class="items" data-bind="foreach: value.buckets">
                        <li class="item">
                            <a href="javascript:void(0)" data-bind="text: key, attr: { 'data-filter-name': $parent.key }" class="apply-filter"></a>
                            <span class="count" data-bind="text: doc_count"><span class="filter-count-label">items</span></span>
                        </li>
                    </ol>
                </div>
            </div>
            <!-- /ko -->
        </div>
        <!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
{"[data-role=facets-sidebar]": {
    "Magento_Ui/js/core/app": {
        "components":{
            "facets":{
                "component":"Ktpl_Elasticsearch\/facets",
                "url":"<?php echo $elasticSearchHelper->getClientUrl()?>",
                "query":"<?php echo $_GET['q'] ?>",
                "availableFilters":<?php echo $availableFacets ?>
            }
        }
    }
}}
</script>
